### PR TITLE
automatic dependency handling

### PR DESCRIPTION
**Pull request by stonecoldhughes**
Do not merge this into master! See build_instructions.txt. Try it out and note any issues in the comments.

### CODE REVIEW

**Comment by dlg0** [comment]
Fails with native appleclang ... (due to openmp missing)

```
(base) dlg-macbookpro3:build dg6$ bash ../cmake.sh
rm: CTestTestfile.cmake: No such file or directory
rm: Makefile: No such file or directory
rm: cmake_install.cmake: No such file or directory
rm: install_manifest.txt: No such file or directory
rm: *test*: No such file or directory
rm: GITR: No such file or directory
rm: *.a: No such file or directory
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Thrust (missing: THRUST_INCLUDE_DIRS)
Downloading thrust...
-- Found Thrust: /Users/dg6/code/GITR/external/thrust/src/thrust_download
Downloading libconfig...
-- Found LibConfig++: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig++.so
-- Found LibConfig: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig.so
-- static LibConfig path: LIBCONFIG_STATIC_LIBRARY-NOTFOUND
-- Failed to find NetCDF interface for CXX
-- Could NOT find NetCDF (missing: NETCDF_HAS_INTERFACES)
Downloading netcdf-c and netcdf-cxx4...
-- Found NetCDF: /usr/local/lib/libnetcdf-cxx4.so;/usr/local/lib/libnetcdf.so
-- Found MPI_C: /usr/local/Cellar/open-mpi/4.0.4_1/lib/libmpi.dylib (found version "3.1")
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/4.0.4_1/lib/libmpi.dylib (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
/Users/dg6/code/GITR/src/EfieldInterp.cpp;/Users/dg6/code/GITR/src/Particle.cpp;/Users/dg6/code/GITR/src/flags.cpp;/Users/dg6/code/GITR/src/interp2d.cpp;/Users/dg6/code/GITR/src/setup.cpp;/Users/dg6/code/GITR/src/utils.cpp;/Users/dg6/code/GITR/test/tests_general.cpp
-- Found LibConfig++: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig++.so
-- Found LibConfig: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig.so
-- static LibConfig path: LIBCONFIG_STATIC_LIBRARY-NOTFOUND
CMake Error at /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindOpenMP.cmake:511 (find_package_handle_standard_args)
  CMakeLists.txt:33 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/dg6/code/GITR/build/CMakeFiles/CMakeOutput.log".
```

**Comment by dlg0** [comment]
I'd think that this should be able to be built without cuda? i.e., thrust is header only (and you download it automatically)

**Comment by dlg0** [comment]
switching to GNU 10.2 ...  still fails due to missing cuda. Is CUDA required even if we don't build for GPUs? (I'm not sure if thrust being header only means you still don't need CUDA for CPU target)
```
(base) dlg-macbookpro3:build dg6$ bash ../cmake.sh
rm: CTestTestfile.cmake: No such file or directory
rm: Makefile: No such file or directory
rm: cmake_install.cmake: No such file or directory
rm: install_manifest.txt: No such file or directory
rm: *test*: No such file or directory
rm: GITR: No such file or directory
rm: *.a: No such file or directory
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/gcc
-- Check for working C compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/g++
-- Check for working CXX compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Thrust (missing: THRUST_INCLUDE_DIRS)
Downloading thrust...
-- Found Thrust: /Users/dg6/code/GITR/external/thrust/src/thrust_download
Downloading libconfig...
-- Found LibConfig++: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig++.so
-- Found LibConfig: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig.so
-- static LibConfig path: LIBCONFIG_STATIC_LIBRARY-NOTFOUND
-- Failed to find NetCDF interface for CXX
-- Could NOT find NetCDF (missing: NETCDF_HAS_INTERFACES)
Downloading netcdf-c and netcdf-cxx4...
-- Found NetCDF: /usr/local/lib/libnetcdf-cxx4.so;/usr/local/lib/libnetcdf.so
-- Found MPI_C: /usr/local/Cellar/open-mpi/4.0.4_1/lib/libmpi.dylib (found version "3.1")
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/4.0.4_1/lib/libmpi.dylib (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
/Users/dg6/code/GITR/src/EfieldInterp.cpp;/Users/dg6/code/GITR/src/Particle.cpp;/Users/dg6/code/GITR/src/flags.cpp;/Users/dg6/code/GITR/src/interp2d.cpp;/Users/dg6/code/GITR/src/setup.cpp;/Users/dg6/code/GITR/src/utils.cpp;/Users/dg6/code/GITR/test/tests_general.cpp
-- Found LibConfig++: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig++.so
-- Found LibConfig: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig.so
-- static LibConfig path: LIBCONFIG_STATIC_LIBRARY-NOTFOUND
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
Enabling CUDA backend
CMake Error at /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find CUDA (missing: CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS
  CUDA_CUDART_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindCUDA.cmake:1104 (find_package_handle_standard_args)
  CMakeLists.txt:91 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/dg6/code/GITR/build/CMakeFiles/CMakeOutput.log".
```

**Comment by dlg0** [comment]
setting 
```
set(CUDA 0)
set(APPLE 1)
```
in `CMakeLists.txt`

gives ...

```
(base) dlg-macbookpro3:build dg6$ bash ../cmake.sh
rm: CTestTestfile.cmake: No such file or directory
rm: Makefile: No such file or directory
rm: cmake_install.cmake: No such file or directory
rm: install_manifest.txt: No such file or directory
rm: *test*: No such file or directory
rm: GITR: No such file or directory
rm: *.a: No such file or directory
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/gcc
-- Check for working C compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/g++
-- Check for working CXX compiler: /Users/dg6/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/gcc-10.2.0-ztygothubd3lo6eiga4p5d3vbwdyvhui/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Thrust (missing: THRUST_INCLUDE_DIRS)
Downloading thrust...
-- Found Thrust: /Users/dg6/code/GITR/external/thrust/src/thrust_download
Downloading libconfig...
-- Found LibConfig++: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig++.so
-- Found LibConfig: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig.so
-- static LibConfig path: LIBCONFIG_STATIC_LIBRARY-NOTFOUND
-- Failed to find NetCDF interface for CXX
-- Could NOT find NetCDF (missing: NETCDF_HAS_INTERFACES)
Downloading netcdf-c and netcdf-cxx4...
-- Found NetCDF: /usr/local/lib/libnetcdf-cxx4.so;/usr/local/lib/libnetcdf.so
-- Found MPI_C: /usr/local/Cellar/open-mpi/4.0.4_1/lib/libmpi.dylib (found version "3.1")
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/4.0.4_1/lib/libmpi.dylib (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
/Users/dg6/code/GITR/src/EfieldInterp.cpp;/Users/dg6/code/GITR/src/Particle.cpp;/Users/dg6/code/GITR/src/flags.cpp;/Users/dg6/code/GITR/src/interp2d.cpp;/Users/dg6/code/GITR/src/setup.cpp;/Users/dg6/code/GITR/src/utils.cpp;/Users/dg6/code/GITR/test/tests_general.cpp
-- Found LibConfig++: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig++.so
-- Found LibConfig: /Users/dg6/code/GITR/external/libconfig/src/libconfig_download-build/out/libconfig.so
-- static LibConfig path: LIBCONFIG_STATIC_LIBRARY-NOTFOUND
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
CMake Error at CMakeLists.txt:168 (target_link_libraries):
  Cannot specify link libraries for target "GITR" which is not built by this
  project.


-- Configuring incomplete, errors occurred!
See also "/Users/dg6/code/GITR/build/CMakeFiles/CMakeOutput.log".
```

**Comment by dlg0** [comment]
i also tried on fusiont6 (without loading CUDA) and got further, but looks to fail during the netcdf-c configure ...

```
[ 93%] Built target zmapio
[ 93%] Built target zisjson
[ 94%] Built target tst_zchunks
[ 95%] Built target zhex
[ 95%] Built target ut_json
[ 96%] Built target ut_map
[ 96%] Built target tst_zchunks2
[ 97%] Built target ut_mapapi
[ 98%] Built target ut_chunking
[ 99%] Built target tst_zchunks3
[ 99%] Built target tst_fillonlyz
[ 99%] Built target tst_chunkcases
[ 99%] Built target ut_projections
[ 99%] Built target ncdumpchunks
[100%] Built target zs3parse
Install the project...
-- Install configuration: "DEBUG"
-- Installing: /usr/local/lib/pkgconfig/netcdf.pc
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/dg6/code/GITR/external/netcdf-c/src/netcdf-c_download-build/netcdf.pc"
  to "/usr/local/lib/pkgconfig/netcdf.pc".


Makefile:73: recipe for target 'install' failed
make[3]: *** [install] Error 1
CMakeFiles/netcdf-c_download.dir/build.make:73: recipe for target '../external/netcdf-c/src/netcdf-c_download-stamp/netcdf-c_download-install' failed
make[2]: *** [../external/netcdf-c/src/netcdf-c_download-stamp/netcdf-c_download-install] Error 2
CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/netcdf-c_download.dir/all' failed
make[1]: *** [CMakeFiles/netcdf-c_download.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by stonecoldhughes** [comment]
@dlg0 Thank you for testing this out! In my testing, this was only confirmed to work on fusiont6 with CUDA=1 and everything else turned off. CPU support will be coming very soon! I will remember to put details like this in the original comment in the future.

**Comment by stonecoldhughes** [comment]
@dlg0 Thank you for testing this out! In my testing, this was only confirmed to work on fusiont6 with CUDA=1 and everything else turned off. CPU support will be the next thing coming to this branch. I will remember to put more informative details like this in the original comment in the future.

**Pull request closed without merging**
