### PR TITLE
Get GPU build working

### PR DESCRIPTION
**Pull request by stonecoldhughes**
CPU build works but GPU build does not. Heavy refactoring of source code will be necessary.

### CODE REVIEW

**Comment by dlg0** [comment]
The code built for GPUs before ... why does it need "heavy refactoring"?

**Comment by dlg0** [comment]
@tyounkin there are soooooo many files in this repo. What are the bulk of them for? How many files does each run require?

**Comment by dlg0** [comment]
@stonecoldhughes @tyounkin heellooooo?

**Comment by tyounkin** [comment]
@dlg0 for many of the examples, we have data files, processing scripts, input files (to GITR), and processing scripts. The data and input files are the large ones. @stonecoldhughes has moved all of the non-source files into a certain folder. We have had some email discussion about these various types of files and how to organize other repos to hold them. We have not acted to create an actual GITR project with multiple repos yet.

**Comment by dlg0** [comment]
@tyounkin How many input files are required for a GITR run, and how many example cases are in the repo?

**Comment by dlg0** [comment]
> The code built for GPUs before ... why does it need "heavy refactoring"?

@stonecoldhughes ?

**Comment by kumargp** [comment]
I thought some information from my experience may be useful. In order to run on GPU on AiMOS at RPI, I had to remove the use of standard namespace (doesn't work for Kokkos or CUDA) at several places, and some other host function calls which happened to be used only for debugging. The fork is https://github.com/SCOREC/GITR/tree/gitr-double. This is also a double precision version of GITR that was used for comparing results with GITRm.

**Comment by stonecoldhughes** [comment]
> I thought some information from my experience may be useful. In order to run on GPU on AiMOS at RPI, I had to remove the use of standard namespace (doesn't work for Kokkos or CUDA) at several places, and some other host function calls which happened to be used only for debugging. The fork is https://github.com/SCOREC/GITR/tree/gitr-double. This is also a double precision version of GITR that was used for comparing results with GITRm.

@kumargp thank you, I will definitely reference this

**Comment by stonecoldhughes** [comment]
> > The code built for GPUs before ... why does it need "heavy refactoring"?
> 
> @stonecoldhughes ?

@dlg0 I should have provided more context. For the GPU build system to mirror the modularity of the CPU build system featured on the branch build/gpu, the source code will need to be refactored to be more modular. This is because the host and device code are intermingled. This is not to say that the master branch needs heavy refactoring in order for the GPU build to work.

**Comment by stonecoldhughes** [comment]
> @tyounkin How many input files are required for a GITR run, and how many example cases are in the repo?

@dlg0 Tim and I will work on compiling some curated example runs of GITR. The input decks slated to be moved to dedicated repositories will be a good source of candidates for these.

**Pull request closed without merging**
